// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAly_2eTLUNibWwZKjcFcajGSIIqZ28ACU',
    appId: '1:387865531845:web:41423ac7ae5e0ae9bde7ac',
    messagingSenderId: '387865531845',
    projectId: 'panaderia-8fb24',
    authDomain: 'panaderia-8fb24.firebaseapp.com',
    storageBucket: 'panaderia-8fb24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfSKyf2MMAJP4TkXl1kywBKgHSPHn2wuo',
    appId: '1:387865531845:android:cb237514a93def7cbde7ac',
    messagingSenderId: '387865531845',
    projectId: 'panaderia-8fb24',
    storageBucket: 'panaderia-8fb24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSB8aMSKtVEFHBbeSE-NeS1w84tOXn7cA',
    appId: '1:387865531845:ios:aa1468f6cd79b576bde7ac',
    messagingSenderId: '387865531845',
    projectId: 'panaderia-8fb24',
    storageBucket: 'panaderia-8fb24.appspot.com',
    iosBundleId: 'com.example.panaderia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSB8aMSKtVEFHBbeSE-NeS1w84tOXn7cA',
    appId: '1:387865531845:ios:aa1468f6cd79b576bde7ac',
    messagingSenderId: '387865531845',
    projectId: 'panaderia-8fb24',
    storageBucket: 'panaderia-8fb24.appspot.com',
    iosBundleId: 'com.example.panaderia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAly_2eTLUNibWwZKjcFcajGSIIqZ28ACU',
    appId: '1:387865531845:web:9e78b48700e6c18bbde7ac',
    messagingSenderId: '387865531845',
    projectId: 'panaderia-8fb24',
    authDomain: 'panaderia-8fb24.firebaseapp.com',
    storageBucket: 'panaderia-8fb24.appspot.com',
  );
}
